# Generated by Django 3.2 on 2023-11-30 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atributo',
            fields=[
                ('atributo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_atributo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Caracteristica',
            fields=[
                ('caracteristica', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_caracteristica', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('evaluacion', models.AutoField(primary_key=True, serialize=False)),
                ('calificacion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=150)),
                ('objetivo_producto', models.TextField()),
                ('tipo_producto', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subcaracteristica',
            fields=[
                ('subcaracteristica', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_subcaracteristica', models.CharField(max_length=255)),
                ('caracteristica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcaracteristicas', to='core.caracteristica')),
            ],
        ),
        migrations.CreateModel(
            name='Riesgo',
            fields=[
                ('riesgo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_riesgo', models.CharField(max_length=255)),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riesgos', to='core.evaluacion')),
            ],
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('resultado', models.AutoField(primary_key=True, serialize=False)),
                ('resultado_nom', models.CharField(max_length=255)),
                ('atributo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='core.atributo')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='core.evaluacion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Requisito',
            fields=[
                ('requisito', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('atributo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitos', to='core.atributo')),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id_proyecto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_proyecto', models.CharField(max_length=150)),
                ('fecha_proyecto', models.DateField()),
                ('requisito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to='core.requisito')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='core.proyecto'),
        ),
        migrations.CreateModel(
            name='Ponderacion',
            fields=[
                ('ponderacion', models.AutoField(primary_key=True, serialize=False)),
                ('ponderado', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ponderado_atributo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ponderado_subcaracteristica', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ponderado_caracteristica', models.DecimalField(decimal_places=2, max_digits=5)),
                ('atributo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ponderaciones', to='core.atributo')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ponderaciones', to='core.evaluacion')),
            ],
        ),
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('informe', models.AutoField(primary_key=True, serialize=False)),
                ('informe_recomendaciones', models.TextField()),
                ('informe_general', models.TextField()),
                ('informe_detallado', models.TextField()),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.evaluacion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto')),
                ('resultado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informes', to='core.resultado')),
            ],
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='ponderacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='core.ponderacion'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='core.producto'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='riesgo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='core.riesgo'),
        ),
        migrations.AddField(
            model_name='atributo',
            name='caracteristica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atributos', to='core.caracteristica'),
        ),
        migrations.AddField(
            model_name='atributo',
            name='ponderacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atributos_ponderacion', to='core.ponderacion'),
        ),
        migrations.AddField(
            model_name='atributo',
            name='requisito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atributos', to='core.requisito'),
        ),
        migrations.AddField(
            model_name='atributo',
            name='resultado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atributos', to='core.resultado'),
        ),
        migrations.AddField(
            model_name='atributo',
            name='subcaracteristica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atributos', to='core.subcaracteristica'),
        ),
    ]
